services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - OPENVPN_MSSFIX=1400
      - OPENVPN_PROTOCOL=udp
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - UPDATER_PERIOD=24h
      - TZ=${TIMEZONE}
    ports:
      - ${QBIT_WEBUI_PORT}:8080/tcp
      - ${QBIT_TORRENT_PORT}:6881/tcp
      - ${QBIT_TORRENT_PORT}:6881/udp
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/gluetun_config:/gluetun

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${QBIT_TORRENT_PORT}
    volumes:
      - ${BASE_PATH}/qbit_config:/config
      - ${BASE_PATH}/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
      - ${BASE_PATH}:/downloads
    restart: unless-stopped